import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useChat } from '../context/ChatContext';
import { db } from '../firebase';
import { doc, setDoc, collection, query, where, getDocs } from 'firebase/firestore';
import { motion } from 'framer-motion';
import { User, Phone, CheckCircle2, Wand2, Sparkles, Gem, ArrowRight, X } from 'lucide-react';
import { generateRandom10Digit, generateFancy10Digit, isNumberUnique } from '../utils/NumberGenerator';
import UPIPaymentModal from '../components/UPIPaymentModal';

const ProfileSetup = () => {
  const { user } = useChat();
  const [displayName, setDisplayName] = useState(user?.displayName || '');
  const [phone, setPhone] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [mode, setMode] = useState('free'); // 'free', 'fancy', 'custom'
  const [isAvailable, setIsAvailable] = useState(null); // null, true, false
  const [isChecking, setIsChecking] = useState(false);
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false);
  const navigate = useNavigate();
  
  // Real-time availability check
  useEffect(() => {
    const checkAvailability = async () => {
      if (phone.length === 10) {
        setIsChecking(true);
        const unique = await isNumberUnique(phone);
        setIsAvailable(unique);
        setIsChecking(false);
      } else {
        setIsAvailable(null);
      }
    };

    const timeoutId = setTimeout(checkAvailability, 500); // 500ms debounce
    return () => setTimeout(() => clearTimeout(timeoutId), 0);
  }, [phone]);

  const findUniqueNumber = async (generator) => {
    let num = generator();
    let unique = await isNumberUnique(num);
    let attempts = 0;
    while (!unique && attempts < 10) {
      num = generator();
      unique = await isNumberUnique(num);
      attempts++;
    }
    return num;
  };

  const handleFreeGenerate = async () => {
    setIsGenerating(true);
    const num = await findUniqueNumber(generateRandom10Digit);
    setPhone(num);
    setMode('free');
    setHasAutoGenerated(true);
    setIsGenerating(false);
  };

  const handleFancyGenerate = async () => {
    setIsGenerating(true);
    const fancyNum = await findUniqueNumber(generateFancy10Digit);
    setPhone(fancyNum);
    setMode('fancy');
    setHasAutoGenerated(true);
    setIsGenerating(false);
  };

  const finishSetup = async (phoneValue, paymentData = null) => {
    setLoading(true);
    try {
      // 2. Check if Messaging ID is unique
      const q = query(collection(db, 'users'), where('phone', '==', phoneValue));
      const querySnapshot = await getDocs(q);
      
      if (!querySnapshot.empty) {
        setLoading(false);
        return setError('ID already assigned to another user.');
      }

      // 3. Update/Create User Profile
      const userData = {
        uid: user.uid,
        username: displayName,
        email: user.email,
        avatar: user.photoURL || `https://api.dicebear.com/7.x/avataaars/svg?seed=${displayName}`,
        phone: phoneValue, 
        bio: 'Available',
        status: 'online',
        createdAt: new Date().toISOString(),
        profileComplete: true 
      };

      // Add payment details if it's a fancy number
      if (paymentData) {
        userData.paymentUTR = paymentData.utr;
        userData.paymentProof = paymentData.proofUrl;
        userData.isPremium = true;
      }

      await setDoc(doc(db, 'users', user.uid), userData, { merge: true });

      navigate('/chat');
    } catch (err) {
      console.error(err);
      setError('Connection failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handlePaymentSuccess = async (paymentData) => {
    setIsPaymentModalOpen(false);
    await finishSetup(phone, paymentData);
  };

  const handleSubmit = async (e) => {
    if (e) e.preventDefault();
    setError('');
    
    // 1. Validation
    if (phone.length !== 10 || !/^\d+$/.test(phone)) {
      return setError('Messaging ID must be exactly 10 digits');
    }

    // 2. Flow: If Fancy or Custom, Open Payment Modal. If Free, Finish immediately.
    if (mode === 'fancy' || mode === 'custom') {
        setIsPaymentModalOpen(true);
    } else {
        await finishSetup(phone);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-neo-bg relative overflow-hidden px-6">
      
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ type: "spring", damping: 12 }}
        className="w-full max-w-[500px] neo-glass rounded-3xl p-12 relative z-10 border-neo-border/20 shadow-2xl"
      >
        <div className="flex flex-col items-center mb-10">
          <div className="w-24 h-24 rounded-full flex items-center justify-center mb-6 relative group">
            <div className="absolute inset-0 bg-neo-primary/10 blur-xl group-hover:bg-neo-primary/20 transition-colors" />
            <div className="relative z-10 w-full h-full rounded-full border-2 border-neo-border flex items-center justify-center bg-neo-surface">
                <User size={48} className="text-neo-text-dim" />
            </div>
          </div>
          <h2 className="text-3xl font-black text-neo-text text-center leading-tight tracking-tighter uppercase italic">
            Profile Setup
          </h2>
          <p className="text-neo-text-dim text-xs mt-4 text-center opacity-60 tracking-[0.1em] font-light max-w-[280px]">
             Create your profile and enter your phone number to get started.
          </p>
        </div>

        {error && (
          <div className="bg-neo-pink text-white px-4 py-3 rounded-xl mb-8 text-[11px] font-black uppercase tracking-widest text-center border border-white/10">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-10">
          <div className="space-y-3 relative group">
            <label className="text-[10px] text-neo-text-dim uppercase font-black tracking-[0.3em] ml-1 opacity-100 transition-opacity">Name</label>
            <div className="flex items-center gap-4 border-b border-neo-border focus-within:border-neo-primary transition-all pb-3 px-2">
              <User size={18} className="text-neo-text-dim" />
              <input
                type="text"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                className="w-full bg-transparent border-none outline-none text-neo-text placeholder:text-neo-text-dim/30 text-[18px] font-light"
                placeholder="Ex: John Doe"
                required
              />
            </div>
          </div>

          <div className="space-y-3 relative group">
            <label className="text-[10px] text-neo-text-dim uppercase font-black tracking-[0.3em] ml-1 opacity-100 transition-opacity">Phone Number</label>
            <div className="flex items-center gap-4 border-b border-neo-border focus-within:border-neo-primary transition-all pb-3 px-2">
              <Phone size={18} className="text-neo-text-dim" />
              <input
                type="text"
                maxLength="10"
                value={phone}
                onChange={(e) => {
                  const val = e.target.value.replace(/\D/g, '');
                  if (val.length <= 10) {
                    setPhone(val);
                    // If they are typing, it's a custom ID (unless they use the generators)
                    if (mode !== 'custom') {
                        setMode('custom');
                    }
                    if (!hasAutoGenerated && val.length > 0) {
                        setHasAutoGenerated(true);
                    }
                  }
                }}
                className={`flex-1 bg-transparent border-none outline-none text-neo-text placeholder:text-neo-text-dim/30 placeholder:tracking-normal text-[24px] font-bold tracking-[0.2em] focus:text-neo-primary transition-colors`}
                placeholder="Type your 10-digit ID"
                required
              />
              
              {phone.length === 10 && (
                <div className={`px-3 py-1 rounded-lg text-[9px] font-black uppercase tracking-widest ${mode === 'free' ? 'bg-neo-primary/10 text-neo-primary' : 'bg-neo-pink/10 text-neo-pink'}`}>
                  {mode === 'free' ? 'Free ID' : mode === 'fancy' ? 'Fancy ID' : 'Custom ID'}
                </div>
              )}
              
              {isChecking && (
                <div className="w-5 h-5 border-2 border-neo-primary border-t-transparent rounded-full animate-spin" />
              )}
              
              {!isChecking && isAvailable === true && (
                  <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }}>
                    <CheckCircle2 size={20} className="text-neo-primary" />
                  </motion.div>
              )}

              {!isChecking && isAvailable === false && (
                  <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="flex items-center gap-2">
                    <span className="text-[10px] font-black text-neo-pink uppercase tracking-widest whitespace-nowrap">Taken</span>
                    <X size={20} className="text-neo-pink" />
                  </motion.div>
              )}
            </div>

            {/* Vertical stack for generation buttons to ensure full text visibility */}
            <div className="flex flex-col gap-4 mt-6">
              {(!hasAutoGenerated || phone.length === 0) && !isGenerating && (
                <div className="flex flex-col gap-3">
                  <div className="flex items-center gap-3 mb-1">
                    <div className="h-px bg-neo-border flex-1 opacity-20" />
                    <span className="text-[9px] text-neo-text-dim font-black uppercase tracking-[0.25em] whitespace-nowrap">Express Identity</span>
                    <div className="h-px bg-neo-border flex-1 opacity-20" />
                  </div>
                  <button 
                    type="button"
                    onClick={handleFreeGenerate}
                    className="w-full px-6 py-3.5 neo-glass border-neo-border/50 hover:border-neo-primary text-neo-text-dim hover:text-neo-primary transition-all rounded-2xl flex items-center justify-between group/free"
                  >
                    <div className="flex items-center gap-3">
                        <Wand2 size={16} className="group-hover/free:rotate-12 transition-transform" />
                        <span className="text-[11px] font-black uppercase tracking-widest">Auto-Generate (Random)</span>
                    </div>
                    <span className="text-[9px] font-black uppercase tracking-widest opacity-40">Free</span>
                  </button>
                  <button 
                    type="button"
                    onClick={handleFancyGenerate}
                    className="w-full px-6 py-3.5 bg-neo-primary/10 border border-neo-primary/30 hover:border-neo-primary text-neo-primary transition-all rounded-2xl flex items-center justify-between relative group/gem overflow-hidden"
                  >
                    <div className="flex items-center gap-3 relative z-10">
                        <Gem size={16} className="group-hover/gem:scale-110 transition-transform" />
                        <span className="text-[11px] font-black uppercase tracking-widest text-left">Generate Fancy Number</span>
                    </div>
                    <span className="text-[11px] font-black uppercase tracking-widest relative z-10 px-3 py-1 bg-neo-primary text-white rounded-lg shadow-sm whitespace-nowrap">₹30 to Own</span>
                  </button>
                </div>
              )}

              {hasAutoGenerated && phone.length > 0 && !isGenerating && (
                  <button 
                    type="button"
                    onClick={() => {
                        setPhone('');
                        setMode('free');
                        setHasAutoGenerated(false);
                        setIsAvailable(null);
                    }}
                    className="text-[10px] font-black text-neo-primary uppercase tracking-widest hover:opacity-70 transition-opacity flex items-center gap-2"
                  >
                    <X size={14} /> Clear and try another way
                  </button>
              )}

              {isGenerating && (
                <div className="flex justify-center items-center py-2 gap-2">
                  <div className="flex gap-1">
                    {[0,1,2].map(i => <motion.div key={i} animate={{ opacity: [0.3, 1, 0.3] }} transition={{ repeat: Infinity, delay: i*0.2 }} className="w-1.5 h-1.5 rounded-full bg-neo-primary" />)}
                  </div>
                  <span className="text-[10px] font-black uppercase tracking-widest text-neo-primary animate-pulse">Assigning Unique ID...</span>
                </div>
              )}
            </div>
          </div>
          
          <button
            type="submit"
            disabled={loading || phone.length !== 10}
            className="w-full py-4 mt-4 bg-neo-primary text-white font-black uppercase tracking-[0.3em] text-[12px] italic rounded-full shadow-lg hover:shadow-neo-primary/20 hover:scale-[1.02] active:scale-95 transition-all disabled:opacity-30 disabled:cursor-not-allowed disabled:grayscale"
          >
            {loading ? 'Processing...' : 'Get Started'}
          </button>
        </form>
      </motion.div>
      
      <div className="mt-16 opacity-30 flex items-center gap-3">
        <div className="w-1.5 h-1.5 rounded-full bg-neo-primary animate-ping" />
        <span className="text-[10px] font-black text-neo-text-dim tracking-[0.4em] uppercase">Secure connection ACTIVE</span>
      </div>

      <UPIPaymentModal 
        isOpen={isPaymentModalOpen}
        onClose={() => setIsPaymentModalOpen(false)}
        onSuccess={handlePaymentSuccess}
        displayName={displayName}
        amount={30}
      />
    </div>
  );
};

export default ProfileSetup;
